<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-2RH5LLD" failures="2" tests="4" name="Test" time="23.017" errors="0" timestamp="2024-09-17T13:14:28 CDT">
  <testcase classname="tests.Logintest" name="loginErrorMessageTC01" time="9.767"/>
  <testcase classname="tests.Logintest" name="loginToSalesforceTC02" time="13.369">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://tekarch-a9-dev-ed.develop.my.salesforce.com/setup/forcecomHomepage.apexp?setupid=ForceCom] but found [Home Page ~ Salesforce - Developer Edition]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://tekarch-a9-dev-ed.develop.my.salesforce.com/setup/forcecomHomepage.apexp?setupid=ForceCom] but found [Home Page ~ Salesforce - Developer Edition]
at tests.Logintest.loginToSalesforceTC02(Logintest.java:65)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- loginToSalesforceTC02 -->
  <testcase classname="tests.Logintest" name="loginToSalesforceTC03" time="14.249">
    <failure type="java.lang.AssertionError" message="expected [https://tekarch-a9-dev-ed.develop.my.salesforce.com/setup/forcecomHomepage.apexp?setupid=ForceCom] but found [Home Page ~ Salesforce - Developer Edition]">
      <![CDATA[java.lang.AssertionError: expected [https://tekarch-a9-dev-ed.develop.my.salesforce.com/setup/forcecomHomepage.apexp?setupid=ForceCom] but found [Home Page ~ Salesforce - Developer Edition]
at tests.Logintest.loginToSalesforceTC03(Logintest.java:78)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- loginToSalesforceTC03 -->
  <testcase classname="tests.Developerconsoletest" name="verifydeveloper" time="2.945"/>
  <testcase classname="tests.Basetest" name="@AfterSuite tearDownFinal" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownFinal -->
  <testcase classname="tests.Basetest" name="@BeforeSuite setup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
</testsuite> <!-- Test -->
